//
// Created by thijs on 6/24/23.
//

#ifndef SINDELFINGENENVSENSOR_CONFIG_H
#define SINDELFINGENENVSENSOR_CONFIG_H

#define BME_ADDR 0x76
#define MOISTURE_SENSOR_PIN A0
#define OW_TEMP_PIN D5

#endif //SINDELFINGENENVSENSOR_CONFIG_H
